### ISSUE TITLE
Issue with DoScan in MenuSetup

### ISSUE THREAD

**Issue by lars18th** [wirbel-at-vdr-portal/wirbelscan-dev#2]
Hi @wirbel-at-vdr-portal ,

First of all, sorry to ask for this here. If you want another way to contact, them please address me to the correct _public_ forum/area. IMHO a direct email is not the best method for sharing issues.

In the mean time, I've this issue:
- I'm implementing a single transponder scan for the w_scan_cpp tools. It's easy to implement it reusing your example code of the "vdr-wirbelscancontrol" plugin. However, I've a problem with the initialization when using the 999 scanning type (the one for the one transponder only). The concrete line is this:

https://github.com/wirbel-at-vdr-portal/wirbelscan-dev/blob/e97dc82f46d6e46648d05aaa7ca1660cb54fda93/menusetup.cpp#L567

As you can see, when the `DVB_Type` is `999` the check will never initialize the device. That's because the wSetup.systems[999] is everytime 0. So removing the second part for testing I can initialize without troubles and the tool works as expected. Therefore my question is:
- What you prefer to solve the issue? To change this code, or you know for a workaround? I feel the best is to extract from the userdata the type of the UserTransponder and then when DVB_Type == 999 then use it as the index for the wSetup.systems[]. But perhaps this could be quite complex.

So, please can you comment about this?
Thank you.

**Comment by lars18th** [comment]
FYI, my dirty solution is this:
```
  //  if (DVB_Type == SCAN_NO_DEVICE || ! wSetup.systems[DVB_Type]) {
      if (DVB_Type == SCAN_NO_DEVICE || (! wSetup.systems[DVB_Type] && DVB_Type != SCAN_TRANSPONDER)) {
```

**Comment by wirbel-at-vdr-portal** [comment]
_I feel the best is to extract from the userdata the type of the UserTransponder and then when DVB_Type == 999 then use it as the index for the wSetup.systems[]. But perhaps this could be quite complex._

This sounds like a good idea.

Use cUserTransponder(uint32_t * Data) and call it's member Type() to read it.

**Comment by wirbel-at-vdr-portal** [comment]
Solution could look like this..

```
--- menusetup.cpp       2023-10-01 13:42:05.326559754 +0200
+++ menusetup.cpp.new   2023-10-01 13:44:37.284672192 +0200
@@ -15,6 +15,7 @@
 #include "wirbelscan.h"
 #include "scanner.h"
 #include "common.h"
+#include "wirbelscan_services.h"

 using namespace COUNTRY;
 extern cScanner* Scanner;
@@ -564,7 +565,14 @@
      return false;
      }
   wSetup.InitSystems();
-  if (DVB_Type == SCAN_NO_DEVICE || ! wSetup.systems[DVB_Type]) {
+  if (DVB_Type == SCAN_TRANSPONDER) {
+     WIRBELSCAN_SERVICE::cUserTransponder t(&wSetup.user[0]);
+     if (! wSetup.systems[t.Type()]) {
+        dlog(0, "ERROR: no device found");
+        return false;
+        }
+     }
+  else if (DVB_Type == SCAN_NO_DEVICE || ! wSetup.systems[DVB_Type]) {
      dlog(0, "ERROR: no device found");
      return false;
      }
```
