### ISSUE TITLE
Where to find satellites.dat file generator?

### ISSUE THREAD

**Issue by khseal** [wirbel-at-vdr-portal/wirbelscan-dev#7]
Can you send me a link or post a generator?
Is this generator suitable for your version?
https://github.com/stefantalpalaru/w_scan2/blob/master/tools/generate_satellites_dat.php

**Comment by wirbel-at-vdr-portal** [comment]
No.

The satellites.dat is plain expert knowledge, therefore there's no such generator that i would like to distribute. The file is generated by tools, but afterwards checked by human, including several scans for each satellite changed.

If someone distributes a tool generating this file without contacting me, i don't support this tool. May work, or may not; I don't care. May break the tool completely.

This internal source file doen't have an versioned interface.
